import type { NextPage } from 'next'
import Head from 'next/head'

import { Attractions } from '../components/attractions/attractions'
import { Contacts } from '../components/contacts'
import { Footer } from '../components/footer/footer'
import { Header } from '../components/header/header'
import { Tours } from '../components/tours/tours'
import { Welcome } from '../components/welcome'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Хакасия</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Header />
        <Welcome />
        <Attractions />
        <Tours />
        <Contacts />
        <Footer />
      </body>
    </div >
  )
}

export default Home
